### ISSUE TITLE
Huge Problem with Chat

### ISSUE THREAD

**Issue by nyashafrank** [steevejoseph/bazaar-frontend#38]
will fix later today

**Comment by abeSanchez** [comment]
ok

**Comment by abeSanchez** [comment]
OH

**Comment by steevejoseph** [comment]
@nyashafrank mind detailing the problem?

**Comment by nyashafrank** [comment]
oh sorry, just saw this. Details mentioned in https://github.com/steevejoseph/bazaar-frontend/pull/41
