### ISSUE TITLE
Fixed set of general tags/categories for creating services instead of text input

### ISSUE THREAD

**Issue by abeSanchez** [steevejoseph/bazaar-frontend#9]
Will make it easier to split services by tags

**Comment by steevejoseph** [comment]
@nyashafrank @abeSanchez What are your thoughts on these?

*  "Graphics & Design",
* "Digital Marketing",
* "Writing & Translation",
* "Video & Animation",
* "Music & Audio",
* "Programming & Tech",
* "Business",
* "Fun & Lifestyle",
* "Lessons/Tutoring",
* "Event Management",
* "Beauty",
* "E-Commerce",
* "Photography",

**Comment by nyashafrank** [comment]
These sound great! But, what about things like textbooks, furniture, etc... Things that aren't technically services, just items.

**Comment by nyashafrank** [comment]
Or is the app strictly for services?
